versionsVersion=0.54.0
springDependencyManagementVersion=1.1.7
springBootVersion=4.1.0

argsVersion=2.37
commonsTextVersion=1.15.0
commonsValidatorVersion=1.10.1
flapdoodleEmbedMongoVersion=4.33.0
junitVersion=6.1.2
smalltoolsVersion=4.4.0
springdocOpenApiVersion=3.0.3
springSessionDataMongodbVersion=4.0.0-M2
