versionsVersion=0.64.0
springDependencyManagementVersion=1.1.7
springBootVersion=4.1.1

argsVersion=2.37
commonsTextVersion=1.15.0
commonsValidatorVersion=1.11.0
flapdoodleEmbedMongoVersion=5.0.0
junitVersion=6.1.3
smalltoolsVersion=4.4.0
springdocOpenApiVersion=3.1.1
springSessionDataMongodbVersion=4.0.0-M2
